const aldeanos = ["Fibrilio", "Narciso", "Vacarena", "Tendo", "Nendo"];

console.log(aldeanos[0]);
console.log(aldeanos[1]);
console.log(aldeanos[2]);
console.log(aldeanos[3]);
console.log(aldeanos[4]);
console.log("--------------------------------------");

aldeanos.push("Cervasio");
console.log(aldeanos[0]);
console.log(aldeanos[1]);
console.log(aldeanos[2]);
console.log(aldeanos[3]);
console.log(aldeanos[4]);
console.log(aldeanos[5]);
aldeanos.reverse();
console.log(aldeanos[0]);
console.log(aldeanos[1]);
console.log(aldeanos[2]);
console.log(aldeanos[3]);
console.log(aldeanos[4]);
console.log(aldeanos[5]);
aldeanos.splice(0,1,"jairo");
console.log(aldeanos[0]);
console.log(aldeanos[1]);
console.log(aldeanos[2]);
console.log(aldeanos[3]);
console.log(aldeanos[4]);
console.log(aldeanos[5]);
